Repository KSP-KOS/EditorTools, pull requests merged in 2020-10, with the labels that each got.

#73 [idea] Add simple find usage test, fix "common ancestor" crash
  IDEA/src/main/java/ksp/kos/ideaplugin/psi/KerboScriptNamedElement.kt
  IDEA/src/test/java/ksp/kos/ideaplugin/KerboScriptFindUsagesProviderTest.kt
  IDEA/src/test/java/ksp/kos/ideaplugin/annotator/KerboScriptAnnotatorTest.kt
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/Imported1.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/Imported3.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/Imported5.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/Imported6.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/Test.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/imported_inner/Imported2.ks
  IDEA/src/test/testData/annotatorUndefinedVariableErrors/imported_inner/Imported4.ks
  IDEA/src/test/testData/findUsages/Basic.ks
Labels: Status: In Progress, bug-fix

#74 [idea] Fix overwriting of LocalContext cache
  IDEA/src/main/java/ksp/kos/ideaplugin/annotator/KerboScriptAnnotator.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/psi/impl/KerboScriptScopeImpl.java
  IDEA/src/main/java/ksp/kos/ideaplugin/psi/impl/KerboScriptScopeImpl.kt
Labels: Status: Completed, bug-fix

#66 [IDEA] Add auto completion for basic keywords
  .github/workflows/idea-gradle-build-and-test.yml
  IDEA/build.gradle.kts
  IDEA/gradlew
  IDEA/src/main/java/ksp/kos/ideaplugin/Magic.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/completion/KerboScriptCompletionContributor.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/completion/KerboScriptKeywordProvider.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/completion/KerboScriptTypedHandler.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/highlighting/KerboScriptHighlightFilter.java
  IDEA/src/main/java/ksp/kos/ideaplugin/highlighting/KerboScriptPairedBraceMatcher.kt
  IDEA/src/main/java/ksp/kos/ideaplugin/highlighting/KerboScriptSyntaxHighlighter.java
  IDEA/src/main/java/ksp/kos/ideaplugin/highlighting/KerboScriptSyntaxHighlighterFactory.java
  IDEA/src/main/resources/META-INF/plugin.xml
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/InlineFile.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/KerboScriptFindUsagesProviderTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/KerboScriptPlatformTestBase.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/annotator/KerboScriptAnnotatorTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/completion/KerboScriptKeywordCompletionTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/parsing/KerboScriptParsingTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/refactoring/KerboScriptDifferentiateTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/refactoring/KerboScriptInlineHandlerTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/refactoring/KerboScriptNormalizeTest.kt
  IDEA/src/test/kotlin/ksp/kos/ideaplugin/refactoring/KerboScriptSimplifyTest.kt
Labels: Status: In Progress, feature
